App live on https://trackstar-api.onrender.com

// Create new user
{
  "oauthId": "github_999888777",
  "provider": "github", 
  "name": "Test User",
  "email": "test@example.com",
  "username": "testuser"
}

//Create new task
{
  "userId": "replace",
  "title": "Buy groceries",
  "description": "Milk, eggs, bread, and fruits",
  "priority": "medium",
  "category": "personal"
}