App live on https://trackstar-api.onrender.com

// Create new user
{
  "providerId": "test_12345",
  "provider": "github",
  "name": "Test User",
  "email": "test@example.com",
  "username": "testuser"
}

//Create new task
{
  "title": "Complete Week 5 Project",
  "description": "Finish the TrackStar API with full CRUD operations",
  "priority": "high",
  "userId": "Replace_with_userId"
}